source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "puma", "~> 8.0"
gem "async", "~> 2.42"
gem "grpc", "~> 1.81"
gem "gruf", "~> 2.22"
gem "connection_pool", "~> 3.0"

group :external_services do
  gem "pg", "~> 1.6"
  gem "redis", "~> 5.4"
end
